name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Change this to your default branch if different

env:
  AWS_REGION: us-east-1  # Change this to your AWS region
  ECR_REPOSITORY: 834352307282.dkr.ecr.us-east-1.amazonaws.com/jeetrepo  # Update with your ECR repository URI
  IMAGE_TAG: latest  # You can modify this to use a unique tag if needed
  AWS_ACCESS_KEY_ID: AKIA4EQ2F3RJLP7OP23D  # Replace with your actual AWS access key ID
  AWS_SECRET_ACCESS_KEY: JCpQcpS3fKrCfssRQ+pjD1TI5GqQAV9IORPVvrbB  # Replace with your actual AWS secret access key

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          echo "Configuring AWS CLI..."
          echo "[default]" > ~/.aws/config
          echo "region = $AWS_REGION" >> ~/.aws/config
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          echo "Logging in to Amazon ECR..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

      - name: Build Docker image
        run: |
          echo "Building the Docker image..."
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Docker image to ECR
        run: |
          echo "Pushing the Docker image..."
          docker push $ECR_REPOSITORY:$IMAGE_TAG
